// This file is auto-generated by @hey-api/openapi-ts

export const AuthorReadSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        username: {
            type: 'string',
            title: 'Username',
            description: 'Author\'s handle.',
            examples: [
                'barista'
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'username'
    ],
    title: 'AuthorRead',
    description: 'Minimal public projection of a user, embedded as the author of a brew or tasting.'
} as const;

export const BeanCreateSchema = {
    properties: {
        origin_country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origin Country',
            description: 'Country of origin.',
            examples: [
                'Ethiopia'
            ]
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region',
            description: 'Growing region.',
            examples: [
                'Guji'
            ]
        },
        producer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Producer',
            description: 'Farm or producer.',
            examples: [
                'Tabe Burka'
            ]
        },
        variety: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variety',
            description: 'Coffee variety.',
            examples: [
                'Heirloom'
            ]
        },
        process: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'washed',
                        'natural',
                        'honey',
                        'anaerobic',
                        'carbonic_maceration',
                        'other'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Process',
            description: 'Post-harvest process.',
            examples: [
                'washed'
            ]
        },
        roast_level: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'light',
                        'medium_light',
                        'medium',
                        'medium_dark',
                        'dark'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roast Level',
            description: 'Roast level.',
            examples: [
                'medium_light'
            ]
        },
        roast_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roast Date',
            description: 'Roast date.',
            examples: [
                '2026-07-01'
            ]
        },
        purchase_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchase Date',
            description: 'Purchase date.',
            examples: [
                '2026-07-05'
            ]
        },
        weight_grams: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight Grams',
            description: 'Bag weight in grams.',
            examples: [
                250
            ]
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price',
            description: 'Price paid for the bag.',
            examples: [
                '18.50'
            ]
        },
        altitude_masl: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Altitude Masl',
            description: 'Growing altitude (metres above sea level).',
            examples: [
                2100
            ]
        },
        tasting_notes_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tasting Notes Label',
            description: 'Tasting notes printed on the bag.',
            examples: [
                'Peach, jasmine, black tea'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Your own notes.',
            examples: [
                'Great as filter'
            ]
        },
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name',
            description: 'Coffee name.',
            examples: [
                'Guji Natural'
            ]
        },
        roaster: {
            type: 'string',
            title: 'Roaster',
            description: 'Roaster name. Matched case-insensitively; created if it does not exist yet.',
            examples: [
                'Nomad Coffee'
            ]
        },
        is_finished: {
            type: 'boolean',
            title: 'Is Finished',
            description: 'Whether the bag is used up.',
            default: false,
            examples: [
                false
            ]
        }
    },
    type: 'object',
    required: [
        'name',
        'roaster'
    ],
    title: 'BeanCreate'
} as const;

export const BeanReadSchema = {
    properties: {
        origin_country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origin Country',
            description: 'Country of origin.',
            examples: [
                'Ethiopia'
            ]
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region',
            description: 'Growing region.',
            examples: [
                'Guji'
            ]
        },
        producer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Producer',
            description: 'Farm or producer.',
            examples: [
                'Tabe Burka'
            ]
        },
        variety: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variety',
            description: 'Coffee variety.',
            examples: [
                'Heirloom'
            ]
        },
        process: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'washed',
                        'natural',
                        'honey',
                        'anaerobic',
                        'carbonic_maceration',
                        'other'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Process',
            description: 'Post-harvest process.',
            examples: [
                'washed'
            ]
        },
        roast_level: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'light',
                        'medium_light',
                        'medium',
                        'medium_dark',
                        'dark'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roast Level',
            description: 'Roast level.',
            examples: [
                'medium_light'
            ]
        },
        roast_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roast Date',
            description: 'Roast date.',
            examples: [
                '2026-07-01'
            ]
        },
        purchase_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchase Date',
            description: 'Purchase date.',
            examples: [
                '2026-07-05'
            ]
        },
        weight_grams: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight Grams',
            description: 'Bag weight in grams.',
            examples: [
                250
            ]
        },
        price: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price',
            description: 'Price paid for the bag.',
            examples: [
                '18.50'
            ]
        },
        altitude_masl: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Altitude Masl',
            description: 'Growing altitude (metres above sea level).',
            examples: [
                2100
            ]
        },
        tasting_notes_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tasting Notes Label',
            description: 'Tasting notes printed on the bag.',
            examples: [
                'Peach, jasmine, black tea'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Your own notes.',
            examples: [
                'Great as filter'
            ]
        },
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        user_id: {
            type: 'integer',
            title: 'User Id',
            description: 'Owner id (who added the bean).',
            examples: [
                1
            ]
        },
        owner: {
            $ref: '#/components/schemas/AuthorRead',
            description: 'Owner (who added the bean).'
        },
        name: {
            type: 'string',
            title: 'Name',
            examples: [
                'Guji Natural'
            ]
        },
        roaster: {
            $ref: '#/components/schemas/RoasterRead',
            description: 'The roaster this bean came from.'
        },
        is_finished: {
            type: 'boolean',
            title: 'Is Finished',
            examples: [
                false
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            examples: [
                '2026-07-05T09:30:00Z'
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'user_id',
        'owner',
        'name',
        'roaster',
        'is_finished',
        'created_at'
    ],
    title: 'BeanRead'
} as const;

export const BeanUpdateSchema = {
    properties: {
        origin_country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origin Country',
            description: 'Country of origin.',
            examples: [
                'Ethiopia'
            ]
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region',
            description: 'Growing region.',
            examples: [
                'Guji'
            ]
        },
        producer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Producer',
            description: 'Farm or producer.',
            examples: [
                'Tabe Burka'
            ]
        },
        variety: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variety',
            description: 'Coffee variety.',
            examples: [
                'Heirloom'
            ]
        },
        process: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'washed',
                        'natural',
                        'honey',
                        'anaerobic',
                        'carbonic_maceration',
                        'other'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Process',
            description: 'Post-harvest process.',
            examples: [
                'washed'
            ]
        },
        roast_level: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'light',
                        'medium_light',
                        'medium',
                        'medium_dark',
                        'dark'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roast Level',
            description: 'Roast level.',
            examples: [
                'medium_light'
            ]
        },
        roast_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roast Date',
            description: 'Roast date.',
            examples: [
                '2026-07-01'
            ]
        },
        purchase_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchase Date',
            description: 'Purchase date.',
            examples: [
                '2026-07-05'
            ]
        },
        weight_grams: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight Grams',
            description: 'Bag weight in grams.',
            examples: [
                250
            ]
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price',
            description: 'Price paid for the bag.',
            examples: [
                '18.50'
            ]
        },
        altitude_masl: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Altitude Masl',
            description: 'Growing altitude (metres above sea level).',
            examples: [
                2100
            ]
        },
        tasting_notes_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tasting Notes Label',
            description: 'Tasting notes printed on the bag.',
            examples: [
                'Peach, jasmine, black tea'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Your own notes.',
            examples: [
                'Great as filter'
            ]
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name',
            description: 'Coffee name.',
            examples: [
                'Guji Natural'
            ]
        },
        roaster: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roaster',
            description: 'Move the bean to this roaster. Matched case-insensitively; created if it does not exist yet.',
            examples: [
                'Nomad Coffee'
            ]
        },
        is_finished: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Finished',
            description: 'Whether the bag is used up.',
            examples: [
                true
            ]
        }
    },
    type: 'object',
    title: 'BeanUpdate',
    description: 'All fields optional; only provided fields are applied (PATCH semantics).'
} as const;

export const Body_auth_loginSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_auth-login'
} as const;

export const BrewCreateSchema = {
    properties: {
        grinder_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grinder Id',
            description: 'Grinder used (equipment id).',
            examples: [
                1
            ]
        },
        brewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brewed At',
            description: 'When it was brewed (defaults to now).',
            examples: [
                '2026-07-12T08:00:00Z'
            ]
        },
        yield_grams: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Yield Grams',
            description: 'Beverage mass in the cup (g).',
            examples: [
                '250'
            ]
        },
        water_grams: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Water Grams',
            description: 'Water used (g); for filter/immersion.',
            examples: [
                '250'
            ]
        },
        grind_setting: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grind Setting',
            description: 'Grinder setting (grinder-specific).',
            examples: [
                '18'
            ]
        },
        water_temp_celsius: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Water Temp Celsius',
            description: 'Water temperature (°C).',
            examples: [
                '93.0'
            ]
        },
        brew_time_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brew Time Seconds',
            description: 'Total brew time (s).',
            examples: [
                150
            ]
        },
        tds_percent: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tds Percent',
            description: 'Measured TDS % (refractometer).',
            examples: [
                '1.35'
            ]
        },
        extraction_yield_percent: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extraction Yield Percent',
            description: 'Extraction yield %; computed and stored from TDS if omitted.',
            examples: [
                '22.50'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Free-form notes.',
            examples: [
                'Even extraction'
            ]
        },
        bean_id: {
            type: 'integer',
            title: 'Bean Id',
            description: 'Bean brewed (any shared bean).',
            examples: [
                1
            ]
        },
        method_id: {
            type: 'integer',
            title: 'Method Id',
            description: 'Brew method id.',
            examples: [
                1
            ]
        },
        dose_grams: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Dose Grams',
            description: 'Dry coffee dose (g).',
            examples: [
                '15'
            ]
        }
    },
    type: 'object',
    required: [
        'bean_id',
        'method_id',
        'dose_grams'
    ],
    title: 'BrewCreate'
} as const;

export const BrewMethodCreateSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name',
            description: 'Unique method name.',
            examples: [
                'V60'
            ]
        },
        category: {
            type: 'string',
            enum: [
                'espresso',
                'filter',
                'immersion'
            ],
            title: 'Category',
            description: 'Brewing family the method belongs to.',
            examples: [
                'filter'
            ]
        },
        default_ratio: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Ratio',
            description: 'Optional default brew ratio (grams of water per gram of coffee).',
            examples: [
                '16.00'
            ]
        }
    },
    type: 'object',
    required: [
        'name',
        'category'
    ],
    title: 'BrewMethodCreate'
} as const;

export const BrewMethodReadSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        name: {
            type: 'string',
            title: 'Name',
            examples: [
                'V60'
            ]
        },
        category: {
            type: 'string',
            title: 'Category',
            examples: [
                'filter'
            ]
        },
        default_ratio: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Ratio',
            examples: [
                '16.00'
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'category',
        'default_ratio'
    ],
    title: 'BrewMethodRead'
} as const;

export const BrewReadSchema = {
    properties: {
        grinder_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grinder Id',
            description: 'Grinder used (equipment id).',
            examples: [
                1
            ]
        },
        brewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brewed At',
            description: 'When it was brewed (defaults to now).',
            examples: [
                '2026-07-12T08:00:00Z'
            ]
        },
        yield_grams: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Yield Grams',
            description: 'Beverage mass in the cup (g).',
            examples: [
                '250'
            ]
        },
        water_grams: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Water Grams',
            description: 'Water used (g); for filter/immersion.',
            examples: [
                '250'
            ]
        },
        grind_setting: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grind Setting',
            description: 'Grinder setting (grinder-specific).',
            examples: [
                '18'
            ]
        },
        water_temp_celsius: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Water Temp Celsius',
            description: 'Water temperature (°C).',
            examples: [
                '93.0'
            ]
        },
        brew_time_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brew Time Seconds',
            description: 'Total brew time (s).',
            examples: [
                150
            ]
        },
        tds_percent: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tds Percent',
            description: 'Measured TDS % (refractometer).',
            examples: [
                '1.35'
            ]
        },
        extraction_yield_percent: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extraction Yield Percent',
            description: 'Extraction yield %; computed and stored from TDS if omitted.',
            examples: [
                '22.50'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Free-form notes.',
            examples: [
                'Even extraction'
            ]
        },
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        user_id: {
            type: 'integer',
            title: 'User Id',
            description: 'Author id (who prepared the brew).',
            examples: [
                1
            ]
        },
        author: {
            $ref: '#/components/schemas/AuthorRead',
            description: 'Author (who prepared the brew).'
        },
        bean_id: {
            type: 'integer',
            title: 'Bean Id',
            examples: [
                1
            ]
        },
        method_id: {
            type: 'integer',
            title: 'Method Id',
            examples: [
                1
            ]
        },
        dose_grams: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Dose Grams',
            examples: [
                '15'
            ]
        },
        ratio: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ratio',
            description: 'Computed brew ratio (never stored).',
            examples: [
                '16.67'
            ]
        },
        diagnostics: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ExtractionDiagnosticsRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'user_id',
        'author',
        'bean_id',
        'method_id',
        'dose_grams'
    ],
    title: 'BrewRead'
} as const;

export const BrewUpdateSchema = {
    properties: {
        grinder_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grinder Id',
            description: 'Grinder used (equipment id).',
            examples: [
                1
            ]
        },
        brewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brewed At',
            description: 'When it was brewed (defaults to now).',
            examples: [
                '2026-07-12T08:00:00Z'
            ]
        },
        yield_grams: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Yield Grams',
            description: 'Beverage mass in the cup (g).',
            examples: [
                '250'
            ]
        },
        water_grams: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Water Grams',
            description: 'Water used (g); for filter/immersion.',
            examples: [
                '250'
            ]
        },
        grind_setting: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grind Setting',
            description: 'Grinder setting (grinder-specific).',
            examples: [
                '18'
            ]
        },
        water_temp_celsius: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Water Temp Celsius',
            description: 'Water temperature (°C).',
            examples: [
                '93.0'
            ]
        },
        brew_time_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brew Time Seconds',
            description: 'Total brew time (s).',
            examples: [
                150
            ]
        },
        tds_percent: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tds Percent',
            description: 'Measured TDS % (refractometer).',
            examples: [
                '1.35'
            ]
        },
        extraction_yield_percent: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extraction Yield Percent',
            description: 'Extraction yield %; computed and stored from TDS if omitted.',
            examples: [
                '22.50'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Free-form notes.',
            examples: [
                'Even extraction'
            ]
        },
        dose_grams: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dose Grams',
            description: 'Dry coffee dose (g).',
            examples: [
                '15'
            ]
        }
    },
    type: 'object',
    title: 'BrewUpdate',
    description: 'Partial update. bean_id/method_id are immutable after creation.'
} as const;

export const EquipmentCreateSchema = {
    properties: {
        type: {
            type: 'string',
            enum: [
                'grinder',
                'espresso_machine',
                'kettle',
                'other'
            ],
            title: 'Type',
            description: 'Kind of equipment.',
            examples: [
                'grinder'
            ]
        },
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name',
            description: 'Model name.',
            examples: [
                'Niche Zero'
            ]
        },
        brand: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand',
            description: 'Manufacturer.',
            examples: [
                'Niche'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Free-form notes.',
            examples: [
                'Single dosing'
            ]
        }
    },
    type: 'object',
    required: [
        'type',
        'name'
    ],
    title: 'EquipmentCreate'
} as const;

export const EquipmentReadSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        type: {
            type: 'string',
            title: 'Type',
            examples: [
                'grinder'
            ]
        },
        name: {
            type: 'string',
            title: 'Name',
            examples: [
                'Niche Zero'
            ]
        },
        brand: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand',
            examples: [
                'Niche'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            examples: [
                'Single dosing'
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            examples: [
                '2026-07-12T18:00:00Z'
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'type',
        'name',
        'brand',
        'notes',
        'created_at'
    ],
    title: 'EquipmentRead'
} as const;

export const ExtractionDiagnosticsReadSchema = {
    properties: {
        strength: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Strength',
            description: 'TDS band: below / within / above target.',
            examples: [
                'within'
            ]
        },
        extraction: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extraction',
            description: 'Extraction-yield band: below / within / above target.',
            examples: [
                'above'
            ]
        }
    },
    type: 'object',
    required: [
        'strength',
        'extraction'
    ],
    title: 'ExtractionDiagnosticsRead',
    description: 'Where the brew sits on the brewing control chart.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const RoasterCreateSchema = {
    properties: {
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country',
            description: 'Country the roaster is based in.',
            examples: [
                'Spain'
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City',
            description: 'City the roaster is based in.',
            examples: [
                'Barcelona'
            ]
        },
        website: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website',
            description: 'Website.',
            examples: [
                'https://nomadcoffee.es'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Your own notes.',
            examples: [
                'Great subscriptions'
            ]
        },
        name: {
            type: 'string',
            title: 'Name',
            description: 'Roaster name (unique, case-insensitive).',
            examples: [
                'Nomad Coffee'
            ]
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'RoasterCreate'
} as const;

export const RoasterMergeSchema = {
    properties: {
        source_id: {
            type: 'integer',
            title: 'Source Id',
            description: 'Roaster to merge away: its beans move to the target and it is deleted.',
            examples: [
                7
            ]
        }
    },
    type: 'object',
    required: [
        'source_id'
    ],
    title: 'RoasterMerge'
} as const;

export const RoasterReadSchema = {
    properties: {
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country',
            description: 'Country the roaster is based in.',
            examples: [
                'Spain'
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City',
            description: 'City the roaster is based in.',
            examples: [
                'Barcelona'
            ]
        },
        website: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website',
            description: 'Website.',
            examples: [
                'https://nomadcoffee.es'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Your own notes.',
            examples: [
                'Great subscriptions'
            ]
        },
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        name: {
            type: 'string',
            title: 'Name',
            examples: [
                'Nomad Coffee'
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            examples: [
                '2026-07-12T18:00:00Z'
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_at'
    ],
    title: 'RoasterRead'
} as const;

export const RoasterUpdateSchema = {
    properties: {
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country',
            description: 'Country the roaster is based in.',
            examples: [
                'Spain'
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City',
            description: 'City the roaster is based in.',
            examples: [
                'Barcelona'
            ]
        },
        website: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website',
            description: 'Website.',
            examples: [
                'https://nomadcoffee.es'
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Your own notes.',
            examples: [
                'Great subscriptions'
            ]
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name',
            description: 'Rename the roaster — every bean referencing it follows.',
            examples: [
                'Nomad Coffee Roasters'
            ]
        }
    },
    type: 'object',
    title: 'RoasterUpdate',
    description: 'All fields optional; only provided fields are applied (PATCH semantics).'
} as const;

export const TastingCreateSchema = {
    properties: {
        aroma: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aroma',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        acidity: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acidity',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        sweetness: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sweetness',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        body: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        bitterness: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bitterness',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        aftertaste: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aftertaste',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        overall: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overall',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        descriptors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Descriptors',
            description: 'Flavor descriptors.',
            examples: [
                [
                    'peach',
                    'jasmine'
                ]
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Free-form notes.',
            examples: [
                'Juicy, clean finish'
            ]
        },
        tasted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tasted At',
            description: 'When tasted (defaults to now).',
            examples: [
                '2026-07-12T08:10:00Z'
            ]
        }
    },
    type: 'object',
    title: 'TastingCreate'
} as const;

export const TastingReadSchema = {
    properties: {
        aroma: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aroma',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        acidity: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acidity',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        sweetness: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sweetness',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        body: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        bitterness: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bitterness',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        aftertaste: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aftertaste',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        overall: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overall',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        descriptors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Descriptors',
            description: 'Flavor descriptors.',
            examples: [
                [
                    'peach',
                    'jasmine'
                ]
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Free-form notes.',
            examples: [
                'Juicy, clean finish'
            ]
        },
        tasted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tasted At',
            description: 'When tasted (defaults to now).',
            examples: [
                '2026-07-12T08:10:00Z'
            ]
        },
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        brew_id: {
            type: 'integer',
            title: 'Brew Id',
            examples: [
                1
            ]
        },
        user_id: {
            type: 'integer',
            title: 'User Id',
            description: 'Taster id (who scored the brew).',
            examples: [
                1
            ]
        },
        author: {
            $ref: '#/components/schemas/AuthorRead',
            description: 'Taster (who scored the brew).'
        }
    },
    type: 'object',
    required: [
        'id',
        'brew_id',
        'user_id',
        'author'
    ],
    title: 'TastingRead'
} as const;

export const TastingUpdateSchema = {
    properties: {
        aroma: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aroma',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        acidity: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Acidity',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        sweetness: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sweetness',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        body: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        bitterness: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bitterness',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        aftertaste: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aftertaste',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        overall: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overall',
            description: 'Score from 1 to 10.',
            examples: [
                8
            ]
        },
        descriptors: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descriptors',
            description: 'Flavor descriptors.',
            examples: [
                [
                    'peach'
                ]
            ]
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes',
            description: 'Free-form notes.',
            examples: [
                'Juicy, clean finish'
            ]
        },
        tasted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tasted At',
            description: 'When tasted (defaults to now).',
            examples: [
                '2026-07-12T08:10:00Z'
            ]
        }
    },
    type: 'object',
    title: 'TastingUpdate',
    description: 'Partial update; only provided fields are applied (PATCH semantics).'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token',
            description: 'JWT access token.',
            examples: [
                'eyJhbGciOiJIUzI1Ni...'
            ]
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer',
            examples: [
                'bearer'
            ]
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token',
    description: 'OAuth2 bearer token response.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email',
            description: 'Login email (unique).',
            examples: [
                'barista@example.com'
            ]
        },
        username: {
            type: 'string',
            maxLength: 32,
            minLength: 3,
            pattern: '^[a-z0-9_.-]+$',
            title: 'Username',
            description: 'Login handle (unique). Lowercase letters, digits, and . _ - only.',
            examples: [
                'barista'
            ]
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password',
            description: 'Plaintext password (8-128 chars); stored hashed.',
            examples: [
                's3cure-passw0rd'
            ]
        }
    },
    type: 'object',
    required: [
        'email',
        'username',
        'password'
    ],
    title: 'UserCreate',
    description: 'Payload for creating a user (admin-only). New users default to role \'user\'.'
} as const;

export const UserReadSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id',
            examples: [
                1
            ]
        },
        email: {
            type: 'string',
            title: 'Email',
            examples: [
                'barista@example.com'
            ]
        },
        username: {
            type: 'string',
            title: 'Username',
            examples: [
                'barista'
            ]
        },
        role: {
            type: 'string',
            title: 'Role',
            examples: [
                'user'
            ]
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            examples: [
                true
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            examples: [
                '2026-07-05T09:30:00Z'
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'email',
        'username',
        'role',
        'is_active',
        'created_at'
    ],
    title: 'UserRead',
    description: 'Public representation of a user (never exposes the password hash).'
} as const;

export const UserUpdateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32,
                    minLength: 3,
                    pattern: '^[a-z0-9_.-]+$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username',
            description: 'New login handle (unique).',
            examples: [
                'head-barista'
            ]
        },
        role: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'admin',
                        'user'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role',
            description: 'New role.',
            examples: [
                'admin'
            ]
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            description: 'Activate or deactivate the account.',
            examples: [
                false
            ]
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Admin-editable user fields: rename, promote/demote and activate/deactivate.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
