// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AuthorRead
 *
 * Minimal public projection of a user, embedded as the author of a brew or tasting.
 */
export type AuthorRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     *
     * Author's handle.
     */
    username: string;
};

/**
 * BeanCreate
 */
export type BeanCreate = {
    /**
     * Origin Country
     *
     * Country of origin.
     */
    origin_country?: string | null;
    /**
     * Region
     *
     * Growing region.
     */
    region?: string | null;
    /**
     * Producer
     *
     * Farm or producer.
     */
    producer?: string | null;
    /**
     * Variety
     *
     * Coffee variety.
     */
    variety?: string | null;
    /**
     * Process
     *
     * Post-harvest process.
     */
    process?: 'washed' | 'natural' | 'honey' | 'anaerobic' | 'carbonic_maceration' | 'other' | null;
    /**
     * Roast Level
     *
     * Roast level.
     */
    roast_level?: 'light' | 'medium_light' | 'medium' | 'medium_dark' | 'dark' | null;
    /**
     * Altitude Masl
     *
     * Growing altitude (metres above sea level).
     */
    altitude_masl?: number | null;
    /**
     * Tasting Notes Label
     *
     * Tasting notes printed on the bag.
     */
    tasting_notes_label?: string | null;
    /**
     * Notes
     *
     * Your own notes.
     */
    notes?: string | null;
    /**
     * Name
     *
     * Coffee name.
     */
    name: string;
    /**
     * Roaster
     *
     * Roaster name. Matched case-insensitively; created if it does not exist yet.
     */
    roaster: string;
};

/**
 * BeanLotCreate
 */
export type BeanLotCreate = {
    /**
     * Roast Date
     *
     * Roast date.
     */
    roast_date?: string | null;
    /**
     * Purchase Date
     *
     * Purchase date.
     */
    purchase_date?: string | null;
    /**
     * Weight Grams
     *
     * Bag weight in grams.
     */
    weight_grams?: number | null;
    /**
     * Price
     *
     * Price paid for the bag.
     */
    price?: number | string | null;
    /**
     * Is Finished
     *
     * Whether the bag is used up.
     */
    is_finished?: boolean;
};

/**
 * BeanLotRead
 */
export type BeanLotRead = {
    /**
     * Roast Date
     *
     * Roast date.
     */
    roast_date?: string | null;
    /**
     * Purchase Date
     *
     * Purchase date.
     */
    purchase_date?: string | null;
    /**
     * Weight Grams
     *
     * Bag weight in grams.
     */
    weight_grams?: number | null;
    /**
     * Price
     *
     * Price paid for the bag.
     */
    price?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Bean Id
     */
    bean_id: number;
    /**
     * User Id
     *
     * Owner id (who bought this bag).
     */
    user_id: number;
    /**
     * Owner (who bought this bag).
     */
    owner: AuthorRead;
    /**
     * Is Finished
     */
    is_finished: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * BeanLotUpdate
 *
 * All fields optional; only provided fields are applied (PATCH semantics).
 */
export type BeanLotUpdate = {
    /**
     * Roast Date
     *
     * Roast date.
     */
    roast_date?: string | null;
    /**
     * Purchase Date
     *
     * Purchase date.
     */
    purchase_date?: string | null;
    /**
     * Weight Grams
     *
     * Bag weight in grams.
     */
    weight_grams?: number | null;
    /**
     * Price
     *
     * Price paid for the bag.
     */
    price?: number | string | null;
    /**
     * Is Finished
     *
     * Whether the bag is used up.
     */
    is_finished?: boolean | null;
};

/**
 * BeanRead
 */
export type BeanRead = {
    /**
     * Origin Country
     *
     * Country of origin.
     */
    origin_country?: string | null;
    /**
     * Region
     *
     * Growing region.
     */
    region?: string | null;
    /**
     * Producer
     *
     * Farm or producer.
     */
    producer?: string | null;
    /**
     * Variety
     *
     * Coffee variety.
     */
    variety?: string | null;
    /**
     * Process
     *
     * Post-harvest process.
     */
    process?: 'washed' | 'natural' | 'honey' | 'anaerobic' | 'carbonic_maceration' | 'other' | null;
    /**
     * Roast Level
     *
     * Roast level.
     */
    roast_level?: 'light' | 'medium_light' | 'medium' | 'medium_dark' | 'dark' | null;
    /**
     * Altitude Masl
     *
     * Growing altitude (metres above sea level).
     */
    altitude_masl?: number | null;
    /**
     * Tasting Notes Label
     *
     * Tasting notes printed on the bag.
     */
    tasting_notes_label?: string | null;
    /**
     * Notes
     *
     * Your own notes.
     */
    notes?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     *
     * Owner id (who added the bean).
     */
    user_id: number;
    /**
     * Owner (who added the bean).
     */
    owner: AuthorRead;
    /**
     * Name
     */
    name: string;
    /**
     * The roaster this bean came from.
     */
    roaster: RoasterRead;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * BeanUpdate
 *
 * All fields optional; only provided fields are applied (PATCH semantics).
 */
export type BeanUpdate = {
    /**
     * Origin Country
     *
     * Country of origin.
     */
    origin_country?: string | null;
    /**
     * Region
     *
     * Growing region.
     */
    region?: string | null;
    /**
     * Producer
     *
     * Farm or producer.
     */
    producer?: string | null;
    /**
     * Variety
     *
     * Coffee variety.
     */
    variety?: string | null;
    /**
     * Process
     *
     * Post-harvest process.
     */
    process?: 'washed' | 'natural' | 'honey' | 'anaerobic' | 'carbonic_maceration' | 'other' | null;
    /**
     * Roast Level
     *
     * Roast level.
     */
    roast_level?: 'light' | 'medium_light' | 'medium' | 'medium_dark' | 'dark' | null;
    /**
     * Altitude Masl
     *
     * Growing altitude (metres above sea level).
     */
    altitude_masl?: number | null;
    /**
     * Tasting Notes Label
     *
     * Tasting notes printed on the bag.
     */
    tasting_notes_label?: string | null;
    /**
     * Notes
     *
     * Your own notes.
     */
    notes?: string | null;
    /**
     * Name
     *
     * Coffee name.
     */
    name?: string | null;
    /**
     * Roaster
     *
     * Move the bean to this roaster. Matched case-insensitively; created if it does not exist yet.
     */
    roaster?: string | null;
};

/**
 * Body_auth-login
 */
export type BodyAuthLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BrewCreate
 */
export type BrewCreate = {
    /**
     * Lot Id
     *
     * Optional: the physical lot this brew came from (must belong to the bean).
     */
    lot_id?: number | null;
    /**
     * Grinder Id
     *
     * Grinder used (equipment id).
     */
    grinder_id?: number | null;
    /**
     * Brewed At
     *
     * When it was brewed (defaults to now).
     */
    brewed_at?: string | null;
    /**
     * Yield Grams
     *
     * Beverage mass in the cup (g).
     */
    yield_grams?: number | string | null;
    /**
     * Water Grams
     *
     * Water used (g); for filter/immersion.
     */
    water_grams?: number | string | null;
    /**
     * Grind Setting
     *
     * Grinder setting (grinder-specific).
     */
    grind_setting?: string | null;
    /**
     * Water Temp Celsius
     *
     * Water temperature (°C).
     */
    water_temp_celsius?: number | string | null;
    /**
     * Brew Time Seconds
     *
     * Total brew time (s).
     */
    brew_time_seconds?: number | null;
    /**
     * Tds Percent
     *
     * Measured TDS % (refractometer).
     */
    tds_percent?: number | string | null;
    /**
     * Extraction Yield Percent
     *
     * Extraction yield %; computed and stored from TDS if omitted.
     */
    extraction_yield_percent?: number | string | null;
    /**
     * Notes
     *
     * Free-form notes.
     */
    notes?: string | null;
    /**
     * Bean Id
     *
     * Bean brewed (any shared bean).
     */
    bean_id: number;
    /**
     * Method Id
     *
     * Brew method id.
     */
    method_id: number;
    /**
     * Dose Grams
     *
     * Dry coffee dose (g).
     */
    dose_grams: number | string;
};

/**
 * BrewMethodCreate
 */
export type BrewMethodCreate = {
    /**
     * Name
     *
     * Unique method name.
     */
    name: string;
    /**
     * Category
     *
     * Brewing family the method belongs to.
     */
    category: 'espresso' | 'filter' | 'immersion';
    /**
     * Default Ratio
     *
     * Optional default brew ratio (grams of water per gram of coffee).
     */
    default_ratio?: number | string | null;
};

/**
 * BrewMethodRead
 */
export type BrewMethodRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Default Ratio
     */
    default_ratio: string | null;
};

/**
 * BrewRead
 */
export type BrewRead = {
    /**
     * Lot Id
     *
     * Optional: the physical lot this brew came from (must belong to the bean).
     */
    lot_id?: number | null;
    /**
     * Grinder Id
     *
     * Grinder used (equipment id).
     */
    grinder_id?: number | null;
    /**
     * Brewed At
     *
     * When it was brewed (defaults to now).
     */
    brewed_at?: string | null;
    /**
     * Yield Grams
     *
     * Beverage mass in the cup (g).
     */
    yield_grams?: string | null;
    /**
     * Water Grams
     *
     * Water used (g); for filter/immersion.
     */
    water_grams?: string | null;
    /**
     * Grind Setting
     *
     * Grinder setting (grinder-specific).
     */
    grind_setting?: string | null;
    /**
     * Water Temp Celsius
     *
     * Water temperature (°C).
     */
    water_temp_celsius?: string | null;
    /**
     * Brew Time Seconds
     *
     * Total brew time (s).
     */
    brew_time_seconds?: number | null;
    /**
     * Tds Percent
     *
     * Measured TDS % (refractometer).
     */
    tds_percent?: string | null;
    /**
     * Extraction Yield Percent
     *
     * Extraction yield %; computed and stored from TDS if omitted.
     */
    extraction_yield_percent?: string | null;
    /**
     * Notes
     *
     * Free-form notes.
     */
    notes?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     *
     * Author id (who prepared the brew).
     */
    user_id: number;
    /**
     * Author (who prepared the brew).
     */
    author: AuthorRead;
    /**
     * Bean Id
     */
    bean_id: number;
    /**
     * Method Id
     */
    method_id: number;
    /**
     * Dose Grams
     */
    dose_grams: string;
    /**
     * Ratio
     *
     * Computed brew ratio (never stored).
     */
    ratio?: string | null;
    diagnostics?: ExtractionDiagnosticsRead | null;
};

/**
 * BrewUpdate
 *
 * Partial update. bean_id/method_id are immutable after creation.
 */
export type BrewUpdate = {
    /**
     * Lot Id
     *
     * Optional: the physical lot this brew came from (must belong to the bean).
     */
    lot_id?: number | null;
    /**
     * Grinder Id
     *
     * Grinder used (equipment id).
     */
    grinder_id?: number | null;
    /**
     * Brewed At
     *
     * When it was brewed (defaults to now).
     */
    brewed_at?: string | null;
    /**
     * Yield Grams
     *
     * Beverage mass in the cup (g).
     */
    yield_grams?: number | string | null;
    /**
     * Water Grams
     *
     * Water used (g); for filter/immersion.
     */
    water_grams?: number | string | null;
    /**
     * Grind Setting
     *
     * Grinder setting (grinder-specific).
     */
    grind_setting?: string | null;
    /**
     * Water Temp Celsius
     *
     * Water temperature (°C).
     */
    water_temp_celsius?: number | string | null;
    /**
     * Brew Time Seconds
     *
     * Total brew time (s).
     */
    brew_time_seconds?: number | null;
    /**
     * Tds Percent
     *
     * Measured TDS % (refractometer).
     */
    tds_percent?: number | string | null;
    /**
     * Extraction Yield Percent
     *
     * Extraction yield %; computed and stored from TDS if omitted.
     */
    extraction_yield_percent?: number | string | null;
    /**
     * Notes
     *
     * Free-form notes.
     */
    notes?: string | null;
    /**
     * Dose Grams
     *
     * Dry coffee dose (g).
     */
    dose_grams?: number | string | null;
};

/**
 * EquipmentCreate
 */
export type EquipmentCreate = {
    /**
     * Type
     *
     * Kind of equipment.
     */
    type: 'grinder' | 'espresso_machine' | 'kettle' | 'other';
    /**
     * Name
     *
     * Model name.
     */
    name: string;
    /**
     * Brand
     *
     * Manufacturer.
     */
    brand?: string | null;
    /**
     * Notes
     *
     * Free-form notes.
     */
    notes?: string | null;
};

/**
 * EquipmentRead
 */
export type EquipmentRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Brand
     */
    brand: string | null;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ExtractionDiagnosticsRead
 *
 * Where the brew sits on the brewing control chart.
 */
export type ExtractionDiagnosticsRead = {
    /**
     * Strength
     *
     * TDS band: below / within / above target.
     */
    strength: string | null;
    /**
     * Extraction
     *
     * Extraction-yield band: below / within / above target.
     */
    extraction: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RoasterCreate
 */
export type RoasterCreate = {
    /**
     * Country
     *
     * Country the roaster is based in.
     */
    country?: string | null;
    /**
     * City
     *
     * City the roaster is based in.
     */
    city?: string | null;
    /**
     * Website
     *
     * Website.
     */
    website?: string | null;
    /**
     * Notes
     *
     * Your own notes.
     */
    notes?: string | null;
    /**
     * Name
     *
     * Roaster name (unique, case-insensitive).
     */
    name: string;
};

/**
 * RoasterMerge
 */
export type RoasterMerge = {
    /**
     * Source Id
     *
     * Roaster to merge away: its beans move to the target and it is deleted.
     */
    source_id: number;
};

/**
 * RoasterRead
 */
export type RoasterRead = {
    /**
     * Country
     *
     * Country the roaster is based in.
     */
    country?: string | null;
    /**
     * City
     *
     * City the roaster is based in.
     */
    city?: string | null;
    /**
     * Website
     *
     * Website.
     */
    website?: string | null;
    /**
     * Notes
     *
     * Your own notes.
     */
    notes?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RoasterUpdate
 *
 * All fields optional; only provided fields are applied (PATCH semantics).
 */
export type RoasterUpdate = {
    /**
     * Country
     *
     * Country the roaster is based in.
     */
    country?: string | null;
    /**
     * City
     *
     * City the roaster is based in.
     */
    city?: string | null;
    /**
     * Website
     *
     * Website.
     */
    website?: string | null;
    /**
     * Notes
     *
     * Your own notes.
     */
    notes?: string | null;
    /**
     * Name
     *
     * Rename the roaster — every bean referencing it follows.
     */
    name?: string | null;
};

/**
 * TastingCreate
 */
export type TastingCreate = {
    /**
     * Aroma
     *
     * Score from 1 to 10.
     */
    aroma?: number | null;
    /**
     * Acidity
     *
     * Score from 1 to 10.
     */
    acidity?: number | null;
    /**
     * Sweetness
     *
     * Score from 1 to 10.
     */
    sweetness?: number | null;
    /**
     * Body
     *
     * Score from 1 to 10.
     */
    body?: number | null;
    /**
     * Bitterness
     *
     * Score from 1 to 10.
     */
    bitterness?: number | null;
    /**
     * Aftertaste
     *
     * Score from 1 to 10.
     */
    aftertaste?: number | null;
    /**
     * Overall
     *
     * Score from 1 to 10.
     */
    overall?: number | null;
    /**
     * Descriptors
     *
     * Flavor descriptors.
     */
    descriptors?: Array<string>;
    /**
     * Notes
     *
     * Free-form notes.
     */
    notes?: string | null;
    /**
     * Tasted At
     *
     * When tasted (defaults to now).
     */
    tasted_at?: string | null;
};

/**
 * TastingRead
 */
export type TastingRead = {
    /**
     * Aroma
     *
     * Score from 1 to 10.
     */
    aroma?: number | null;
    /**
     * Acidity
     *
     * Score from 1 to 10.
     */
    acidity?: number | null;
    /**
     * Sweetness
     *
     * Score from 1 to 10.
     */
    sweetness?: number | null;
    /**
     * Body
     *
     * Score from 1 to 10.
     */
    body?: number | null;
    /**
     * Bitterness
     *
     * Score from 1 to 10.
     */
    bitterness?: number | null;
    /**
     * Aftertaste
     *
     * Score from 1 to 10.
     */
    aftertaste?: number | null;
    /**
     * Overall
     *
     * Score from 1 to 10.
     */
    overall?: number | null;
    /**
     * Descriptors
     *
     * Flavor descriptors.
     */
    descriptors?: Array<string>;
    /**
     * Notes
     *
     * Free-form notes.
     */
    notes?: string | null;
    /**
     * Tasted At
     *
     * When tasted (defaults to now).
     */
    tasted_at?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Brew Id
     */
    brew_id: number;
    /**
     * User Id
     *
     * Taster id (who scored the brew).
     */
    user_id: number;
    /**
     * Taster (who scored the brew).
     */
    author: AuthorRead;
};

/**
 * TastingUpdate
 *
 * Partial update; only provided fields are applied (PATCH semantics).
 */
export type TastingUpdate = {
    /**
     * Aroma
     *
     * Score from 1 to 10.
     */
    aroma?: number | null;
    /**
     * Acidity
     *
     * Score from 1 to 10.
     */
    acidity?: number | null;
    /**
     * Sweetness
     *
     * Score from 1 to 10.
     */
    sweetness?: number | null;
    /**
     * Body
     *
     * Score from 1 to 10.
     */
    body?: number | null;
    /**
     * Bitterness
     *
     * Score from 1 to 10.
     */
    bitterness?: number | null;
    /**
     * Aftertaste
     *
     * Score from 1 to 10.
     */
    aftertaste?: number | null;
    /**
     * Overall
     *
     * Score from 1 to 10.
     */
    overall?: number | null;
    /**
     * Descriptors
     *
     * Flavor descriptors.
     */
    descriptors?: Array<string> | null;
    /**
     * Notes
     *
     * Free-form notes.
     */
    notes?: string | null;
    /**
     * Tasted At
     *
     * When tasted (defaults to now).
     */
    tasted_at?: string | null;
};

/**
 * Token
 *
 * OAuth2 bearer token response.
 */
export type Token = {
    /**
     * Access Token
     *
     * JWT access token.
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 *
 * Payload for creating a user (admin-only). New users default to role 'user'.
 */
export type UserCreate = {
    /**
     * Email
     *
     * Login email (unique).
     */
    email: string;
    /**
     * Username
     *
     * Login handle (unique). Lowercase letters, digits, and . _ - only.
     */
    username: string;
    /**
     * Password
     *
     * Plaintext password (8-128 chars); stored hashed.
     */
    password: string;
};

/**
 * UserRead
 *
 * Public representation of a user (never exposes the password hash).
 */
export type UserRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Role
     */
    role: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserUpdate
 *
 * Admin-editable user fields: rename, promote/demote and activate/deactivate.
 */
export type UserUpdate = {
    /**
     * Username
     *
     * New login handle (unique).
     */
    username?: string | null;
    /**
     * Role
     *
     * New role.
     */
    role?: 'admin' | 'user' | null;
    /**
     * Is Active
     *
     * Activate or deactivate the account.
     */
    is_active?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SystemHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type SystemHealthResponses = {
    /**
     * Response System-Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type SystemHealthResponse = SystemHealthResponses[keyof SystemHealthResponses];

export type AuthLoginData = {
    body: BodyAuthLogin;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthReadCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthReadCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthReadCurrentUserResponse = AuthReadCurrentUserResponses[keyof AuthReadCurrentUserResponses];

export type UsersListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UsersListUsersResponses = {
    /**
     * Response Users-List Users
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type UsersListUsersResponse = UsersListUsersResponses[keyof UsersListUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type RoastersListRoastersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/roasters';
};

export type RoastersListRoastersResponses = {
    /**
     * Response Roasters-List Roasters
     *
     * Successful Response
     */
    200: Array<RoasterRead>;
};

export type RoastersListRoastersResponse = RoastersListRoastersResponses[keyof RoastersListRoastersResponses];

export type RoastersCreateRoasterData = {
    body: RoasterCreate;
    path?: never;
    query?: never;
    url: '/api/v1/roasters';
};

export type RoastersCreateRoasterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoastersCreateRoasterError = RoastersCreateRoasterErrors[keyof RoastersCreateRoasterErrors];

export type RoastersCreateRoasterResponses = {
    /**
     * Successful Response
     */
    201: RoasterRead;
};

export type RoastersCreateRoasterResponse = RoastersCreateRoasterResponses[keyof RoastersCreateRoasterResponses];

export type RoastersDeleteRoasterData = {
    body?: never;
    path: {
        /**
         * Roaster Id
         */
        roaster_id: number;
    };
    query?: never;
    url: '/api/v1/roasters/{roaster_id}';
};

export type RoastersDeleteRoasterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoastersDeleteRoasterError = RoastersDeleteRoasterErrors[keyof RoastersDeleteRoasterErrors];

export type RoastersDeleteRoasterResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RoastersDeleteRoasterResponse = RoastersDeleteRoasterResponses[keyof RoastersDeleteRoasterResponses];

export type RoastersGetRoasterData = {
    body?: never;
    path: {
        /**
         * Roaster Id
         */
        roaster_id: number;
    };
    query?: never;
    url: '/api/v1/roasters/{roaster_id}';
};

export type RoastersGetRoasterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoastersGetRoasterError = RoastersGetRoasterErrors[keyof RoastersGetRoasterErrors];

export type RoastersGetRoasterResponses = {
    /**
     * Successful Response
     */
    200: RoasterRead;
};

export type RoastersGetRoasterResponse = RoastersGetRoasterResponses[keyof RoastersGetRoasterResponses];

export type RoastersUpdateRoasterData = {
    body: RoasterUpdate;
    path: {
        /**
         * Roaster Id
         */
        roaster_id: number;
    };
    query?: never;
    url: '/api/v1/roasters/{roaster_id}';
};

export type RoastersUpdateRoasterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoastersUpdateRoasterError = RoastersUpdateRoasterErrors[keyof RoastersUpdateRoasterErrors];

export type RoastersUpdateRoasterResponses = {
    /**
     * Successful Response
     */
    200: RoasterRead;
};

export type RoastersUpdateRoasterResponse = RoastersUpdateRoasterResponses[keyof RoastersUpdateRoasterResponses];

export type RoastersMergeRoasterData = {
    body: RoasterMerge;
    path: {
        /**
         * Roaster Id
         */
        roaster_id: number;
    };
    query?: never;
    url: '/api/v1/roasters/{roaster_id}/merge';
};

export type RoastersMergeRoasterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoastersMergeRoasterError = RoastersMergeRoasterErrors[keyof RoastersMergeRoasterErrors];

export type RoastersMergeRoasterResponses = {
    /**
     * Successful Response
     */
    200: RoasterRead;
};

export type RoastersMergeRoasterResponse = RoastersMergeRoasterResponses[keyof RoastersMergeRoasterResponses];

export type BeansListBeansData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Mine
         */
        mine?: boolean;
    };
    url: '/api/v1/beans';
};

export type BeansListBeansErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BeansListBeansError = BeansListBeansErrors[keyof BeansListBeansErrors];

export type BeansListBeansResponses = {
    /**
     * Response Beans-List Beans
     *
     * Successful Response
     */
    200: Array<BeanRead>;
};

export type BeansListBeansResponse = BeansListBeansResponses[keyof BeansListBeansResponses];

export type BeansCreateBeanData = {
    body: BeanCreate;
    path?: never;
    query?: never;
    url: '/api/v1/beans';
};

export type BeansCreateBeanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BeansCreateBeanError = BeansCreateBeanErrors[keyof BeansCreateBeanErrors];

export type BeansCreateBeanResponses = {
    /**
     * Successful Response
     */
    201: BeanRead;
};

export type BeansCreateBeanResponse = BeansCreateBeanResponses[keyof BeansCreateBeanResponses];

export type BeansDeleteBeanData = {
    body?: never;
    path: {
        /**
         * Bean Id
         */
        bean_id: number;
    };
    query?: never;
    url: '/api/v1/beans/{bean_id}';
};

export type BeansDeleteBeanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BeansDeleteBeanError = BeansDeleteBeanErrors[keyof BeansDeleteBeanErrors];

export type BeansDeleteBeanResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type BeansDeleteBeanResponse = BeansDeleteBeanResponses[keyof BeansDeleteBeanResponses];

export type BeansGetBeanData = {
    body?: never;
    path: {
        /**
         * Bean Id
         */
        bean_id: number;
    };
    query?: never;
    url: '/api/v1/beans/{bean_id}';
};

export type BeansGetBeanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BeansGetBeanError = BeansGetBeanErrors[keyof BeansGetBeanErrors];

export type BeansGetBeanResponses = {
    /**
     * Successful Response
     */
    200: BeanRead;
};

export type BeansGetBeanResponse = BeansGetBeanResponses[keyof BeansGetBeanResponses];

export type BeansUpdateBeanData = {
    body: BeanUpdate;
    path: {
        /**
         * Bean Id
         */
        bean_id: number;
    };
    query?: never;
    url: '/api/v1/beans/{bean_id}';
};

export type BeansUpdateBeanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BeansUpdateBeanError = BeansUpdateBeanErrors[keyof BeansUpdateBeanErrors];

export type BeansUpdateBeanResponses = {
    /**
     * Successful Response
     */
    200: BeanRead;
};

export type BeansUpdateBeanResponse = BeansUpdateBeanResponses[keyof BeansUpdateBeanResponses];

export type LotsListLotsData = {
    body?: never;
    path: {
        /**
         * Bean Id
         */
        bean_id: number;
    };
    query?: never;
    url: '/api/v1/beans/{bean_id}/lots';
};

export type LotsListLotsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LotsListLotsError = LotsListLotsErrors[keyof LotsListLotsErrors];

export type LotsListLotsResponses = {
    /**
     * Response Lots-List Lots
     *
     * Successful Response
     */
    200: Array<BeanLotRead>;
};

export type LotsListLotsResponse = LotsListLotsResponses[keyof LotsListLotsResponses];

export type LotsCreateLotData = {
    body: BeanLotCreate;
    path: {
        /**
         * Bean Id
         */
        bean_id: number;
    };
    query?: never;
    url: '/api/v1/beans/{bean_id}/lots';
};

export type LotsCreateLotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LotsCreateLotError = LotsCreateLotErrors[keyof LotsCreateLotErrors];

export type LotsCreateLotResponses = {
    /**
     * Successful Response
     */
    201: BeanLotRead;
};

export type LotsCreateLotResponse = LotsCreateLotResponses[keyof LotsCreateLotResponses];

export type LotsDeleteLotData = {
    body?: never;
    path: {
        /**
         * Lot Id
         */
        lot_id: number;
    };
    query?: never;
    url: '/api/v1/lots/{lot_id}';
};

export type LotsDeleteLotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LotsDeleteLotError = LotsDeleteLotErrors[keyof LotsDeleteLotErrors];

export type LotsDeleteLotResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LotsDeleteLotResponse = LotsDeleteLotResponses[keyof LotsDeleteLotResponses];

export type LotsGetLotData = {
    body?: never;
    path: {
        /**
         * Lot Id
         */
        lot_id: number;
    };
    query?: never;
    url: '/api/v1/lots/{lot_id}';
};

export type LotsGetLotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LotsGetLotError = LotsGetLotErrors[keyof LotsGetLotErrors];

export type LotsGetLotResponses = {
    /**
     * Successful Response
     */
    200: BeanLotRead;
};

export type LotsGetLotResponse = LotsGetLotResponses[keyof LotsGetLotResponses];

export type LotsUpdateLotData = {
    body: BeanLotUpdate;
    path: {
        /**
         * Lot Id
         */
        lot_id: number;
    };
    query?: never;
    url: '/api/v1/lots/{lot_id}';
};

export type LotsUpdateLotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LotsUpdateLotError = LotsUpdateLotErrors[keyof LotsUpdateLotErrors];

export type LotsUpdateLotResponses = {
    /**
     * Successful Response
     */
    200: BeanLotRead;
};

export type LotsUpdateLotResponse = LotsUpdateLotResponses[keyof LotsUpdateLotResponses];

export type BrewMethodsListBrewMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/brew-methods';
};

export type BrewMethodsListBrewMethodsResponses = {
    /**
     * Response Brew-Methods-List Brew Methods
     *
     * Successful Response
     */
    200: Array<BrewMethodRead>;
};

export type BrewMethodsListBrewMethodsResponse = BrewMethodsListBrewMethodsResponses[keyof BrewMethodsListBrewMethodsResponses];

export type BrewMethodsCreateBrewMethodData = {
    body: BrewMethodCreate;
    path?: never;
    query?: never;
    url: '/api/v1/brew-methods';
};

export type BrewMethodsCreateBrewMethodErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrewMethodsCreateBrewMethodError = BrewMethodsCreateBrewMethodErrors[keyof BrewMethodsCreateBrewMethodErrors];

export type BrewMethodsCreateBrewMethodResponses = {
    /**
     * Successful Response
     */
    201: BrewMethodRead;
};

export type BrewMethodsCreateBrewMethodResponse = BrewMethodsCreateBrewMethodResponses[keyof BrewMethodsCreateBrewMethodResponses];

export type BrewMethodsGetBrewMethodData = {
    body?: never;
    path: {
        /**
         * Method Id
         */
        method_id: number;
    };
    query?: never;
    url: '/api/v1/brew-methods/{method_id}';
};

export type BrewMethodsGetBrewMethodErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrewMethodsGetBrewMethodError = BrewMethodsGetBrewMethodErrors[keyof BrewMethodsGetBrewMethodErrors];

export type BrewMethodsGetBrewMethodResponses = {
    /**
     * Successful Response
     */
    200: BrewMethodRead;
};

export type BrewMethodsGetBrewMethodResponse = BrewMethodsGetBrewMethodResponses[keyof BrewMethodsGetBrewMethodResponses];

export type EquipmentListEquipmentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/equipment';
};

export type EquipmentListEquipmentResponses = {
    /**
     * Response Equipment-List Equipment
     *
     * Successful Response
     */
    200: Array<EquipmentRead>;
};

export type EquipmentListEquipmentResponse = EquipmentListEquipmentResponses[keyof EquipmentListEquipmentResponses];

export type EquipmentCreateEquipmentData = {
    body: EquipmentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/equipment';
};

export type EquipmentCreateEquipmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EquipmentCreateEquipmentError = EquipmentCreateEquipmentErrors[keyof EquipmentCreateEquipmentErrors];

export type EquipmentCreateEquipmentResponses = {
    /**
     * Successful Response
     */
    201: EquipmentRead;
};

export type EquipmentCreateEquipmentResponse = EquipmentCreateEquipmentResponses[keyof EquipmentCreateEquipmentResponses];

export type EquipmentGetEquipmentData = {
    body?: never;
    path: {
        /**
         * Equipment Id
         */
        equipment_id: number;
    };
    query?: never;
    url: '/api/v1/equipment/{equipment_id}';
};

export type EquipmentGetEquipmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EquipmentGetEquipmentError = EquipmentGetEquipmentErrors[keyof EquipmentGetEquipmentErrors];

export type EquipmentGetEquipmentResponses = {
    /**
     * Successful Response
     */
    200: EquipmentRead;
};

export type EquipmentGetEquipmentResponse = EquipmentGetEquipmentResponses[keyof EquipmentGetEquipmentResponses];

export type BrewsListBrewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Mine
         */
        mine?: boolean;
    };
    url: '/api/v1/brews';
};

export type BrewsListBrewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrewsListBrewsError = BrewsListBrewsErrors[keyof BrewsListBrewsErrors];

export type BrewsListBrewsResponses = {
    /**
     * Response Brews-List Brews
     *
     * Successful Response
     */
    200: Array<BrewRead>;
};

export type BrewsListBrewsResponse = BrewsListBrewsResponses[keyof BrewsListBrewsResponses];

export type BrewsCreateBrewData = {
    body: BrewCreate;
    path?: never;
    query?: never;
    url: '/api/v1/brews';
};

export type BrewsCreateBrewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrewsCreateBrewError = BrewsCreateBrewErrors[keyof BrewsCreateBrewErrors];

export type BrewsCreateBrewResponses = {
    /**
     * Successful Response
     */
    201: BrewRead;
};

export type BrewsCreateBrewResponse = BrewsCreateBrewResponses[keyof BrewsCreateBrewResponses];

export type BrewsDeleteBrewData = {
    body?: never;
    path: {
        /**
         * Brew Id
         */
        brew_id: number;
    };
    query?: never;
    url: '/api/v1/brews/{brew_id}';
};

export type BrewsDeleteBrewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrewsDeleteBrewError = BrewsDeleteBrewErrors[keyof BrewsDeleteBrewErrors];

export type BrewsDeleteBrewResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type BrewsDeleteBrewResponse = BrewsDeleteBrewResponses[keyof BrewsDeleteBrewResponses];

export type BrewsGetBrewData = {
    body?: never;
    path: {
        /**
         * Brew Id
         */
        brew_id: number;
    };
    query?: never;
    url: '/api/v1/brews/{brew_id}';
};

export type BrewsGetBrewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrewsGetBrewError = BrewsGetBrewErrors[keyof BrewsGetBrewErrors];

export type BrewsGetBrewResponses = {
    /**
     * Successful Response
     */
    200: BrewRead;
};

export type BrewsGetBrewResponse = BrewsGetBrewResponses[keyof BrewsGetBrewResponses];

export type BrewsUpdateBrewData = {
    body: BrewUpdate;
    path: {
        /**
         * Brew Id
         */
        brew_id: number;
    };
    query?: never;
    url: '/api/v1/brews/{brew_id}';
};

export type BrewsUpdateBrewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrewsUpdateBrewError = BrewsUpdateBrewErrors[keyof BrewsUpdateBrewErrors];

export type BrewsUpdateBrewResponses = {
    /**
     * Successful Response
     */
    200: BrewRead;
};

export type BrewsUpdateBrewResponse = BrewsUpdateBrewResponses[keyof BrewsUpdateBrewResponses];

export type TastingsListTastingsData = {
    body?: never;
    path: {
        /**
         * Brew Id
         */
        brew_id: number;
    };
    query?: never;
    url: '/api/v1/brews/{brew_id}/tastings';
};

export type TastingsListTastingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TastingsListTastingsError = TastingsListTastingsErrors[keyof TastingsListTastingsErrors];

export type TastingsListTastingsResponses = {
    /**
     * Response Tastings-List Tastings
     *
     * Successful Response
     */
    200: Array<TastingRead>;
};

export type TastingsListTastingsResponse = TastingsListTastingsResponses[keyof TastingsListTastingsResponses];

export type TastingsCreateTastingData = {
    body: TastingCreate;
    path: {
        /**
         * Brew Id
         */
        brew_id: number;
    };
    query?: never;
    url: '/api/v1/brews/{brew_id}/tastings';
};

export type TastingsCreateTastingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TastingsCreateTastingError = TastingsCreateTastingErrors[keyof TastingsCreateTastingErrors];

export type TastingsCreateTastingResponses = {
    /**
     * Successful Response
     */
    201: TastingRead;
};

export type TastingsCreateTastingResponse = TastingsCreateTastingResponses[keyof TastingsCreateTastingResponses];

export type TastingsListAllTastingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Mine
         */
        mine?: boolean;
    };
    url: '/api/v1/tastings';
};

export type TastingsListAllTastingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TastingsListAllTastingsError = TastingsListAllTastingsErrors[keyof TastingsListAllTastingsErrors];

export type TastingsListAllTastingsResponses = {
    /**
     * Response Tastings-List All Tastings
     *
     * Successful Response
     */
    200: Array<TastingRead>;
};

export type TastingsListAllTastingsResponse = TastingsListAllTastingsResponses[keyof TastingsListAllTastingsResponses];

export type TastingsDeleteTastingData = {
    body?: never;
    path: {
        /**
         * Tasting Id
         */
        tasting_id: number;
    };
    query?: never;
    url: '/api/v1/tastings/{tasting_id}';
};

export type TastingsDeleteTastingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TastingsDeleteTastingError = TastingsDeleteTastingErrors[keyof TastingsDeleteTastingErrors];

export type TastingsDeleteTastingResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TastingsDeleteTastingResponse = TastingsDeleteTastingResponses[keyof TastingsDeleteTastingResponses];

export type TastingsGetTastingData = {
    body?: never;
    path: {
        /**
         * Tasting Id
         */
        tasting_id: number;
    };
    query?: never;
    url: '/api/v1/tastings/{tasting_id}';
};

export type TastingsGetTastingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TastingsGetTastingError = TastingsGetTastingErrors[keyof TastingsGetTastingErrors];

export type TastingsGetTastingResponses = {
    /**
     * Successful Response
     */
    200: TastingRead;
};

export type TastingsGetTastingResponse = TastingsGetTastingResponses[keyof TastingsGetTastingResponses];

export type TastingsUpdateTastingData = {
    body: TastingUpdate;
    path: {
        /**
         * Tasting Id
         */
        tasting_id: number;
    };
    query?: never;
    url: '/api/v1/tastings/{tasting_id}';
};

export type TastingsUpdateTastingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TastingsUpdateTastingError = TastingsUpdateTastingErrors[keyof TastingsUpdateTastingErrors];

export type TastingsUpdateTastingResponses = {
    /**
     * Successful Response
     */
    200: TastingRead;
};

export type TastingsUpdateTastingResponse = TastingsUpdateTastingResponses[keyof TastingsUpdateTastingResponses];
