"""initial schema

Revision ID: 1cfe1dd99d74
Revises: 
Create Date: 2026-07-11 13:12:34.601317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cfe1dd99d74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brew_method',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('default_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.CheckConstraint("category IN ('espresso', 'filter', 'immersion')", name='ck_brew_method_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('grinder', 'espresso_machine', 'kettle', 'other')", name='ck_equipment_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'user'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('roaster', sa.Text(), nullable=False),
    sa.Column('origin_country', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('producer', sa.Text(), nullable=True),
    sa.Column('variety', sa.Text(), nullable=True),
    sa.Column('process', sa.Text(), nullable=True),
    sa.Column('roast_level', sa.Text(), nullable=True),
    sa.Column('roast_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('altitude_masl', sa.Integer(), nullable=True),
    sa.Column('tasting_notes_label', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("process IN ('washed', 'natural', 'honey', 'anaerobic', 'carbonic_maceration', 'other')", name='ck_bean_process'),
    sa.CheckConstraint("roast_level IN ('light', 'medium_light', 'medium', 'medium_dark', 'dark')", name='ck_bean_roast_level'),
    sa.CheckConstraint('weight_grams > 0', name='ck_bean_weight_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bean_roaster', 'bean', ['roaster'], unique=False)
    op.create_index('idx_bean_user_id', 'bean', ['user_id'], unique=False)
    op.create_table('brew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.SmallInteger(), nullable=False),
    sa.Column('grinder_id', sa.Integer(), nullable=True),
    sa.Column('brewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dose_grams', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('yield_grams', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('water_grams', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('grind_setting', sa.Text(), nullable=True),
    sa.Column('water_temp_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('brew_time_seconds', sa.Integer(), nullable=True),
    sa.Column('tds_percent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('extraction_yield_percent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('brew_time_seconds > 0', name='ck_brew_time_positive'),
    sa.CheckConstraint('dose_grams > 0', name='ck_brew_dose_positive'),
    sa.CheckConstraint('extraction_yield_percent >= 0', name='ck_brew_ey_nonneg'),
    sa.CheckConstraint('tds_percent >= 0', name='ck_brew_tds_nonneg'),
    sa.CheckConstraint('water_grams > 0', name='ck_brew_water_positive'),
    sa.CheckConstraint('yield_grams > 0', name='ck_brew_yield_positive'),
    sa.ForeignKeyConstraint(['bean_id'], ['bean.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grinder_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['method_id'], ['brew_method.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brew_bean_id', 'brew', ['bean_id'], unique=False)
    op.create_index('idx_brew_brewed_at', 'brew', [sa.literal_column('brewed_at DESC')], unique=False)
    op.create_index('idx_brew_method_id', 'brew', ['method_id'], unique=False)
    op.create_index('idx_brew_user_id', 'brew', ['user_id'], unique=False)
    op.create_table('tasting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aroma', sa.SmallInteger(), nullable=True),
    sa.Column('acidity', sa.SmallInteger(), nullable=True),
    sa.Column('sweetness', sa.SmallInteger(), nullable=True),
    sa.Column('body', sa.SmallInteger(), nullable=True),
    sa.Column('bitterness', sa.SmallInteger(), nullable=True),
    sa.Column('aftertaste', sa.SmallInteger(), nullable=True),
    sa.Column('overall', sa.SmallInteger(), nullable=True),
    sa.Column('descriptors', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tasted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('acidity BETWEEN 1 AND 10', name='ck_tasting_acidity_range'),
    sa.CheckConstraint('aftertaste BETWEEN 1 AND 10', name='ck_tasting_aftertaste_range'),
    sa.CheckConstraint('aroma BETWEEN 1 AND 10', name='ck_tasting_aroma_range'),
    sa.CheckConstraint('bitterness BETWEEN 1 AND 10', name='ck_tasting_bitterness_range'),
    sa.CheckConstraint('body BETWEEN 1 AND 10', name='ck_tasting_body_range'),
    sa.CheckConstraint('overall BETWEEN 1 AND 10', name='ck_tasting_overall_range'),
    sa.CheckConstraint('sweetness BETWEEN 1 AND 10', name='ck_tasting_sweetness_range'),
    sa.ForeignKeyConstraint(['brew_id'], ['brew.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasting_brew_id', 'tasting', ['brew_id'], unique=False)
    op.create_index('idx_tasting_user_id', 'tasting', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasting_user_id', table_name='tasting')
    op.drop_index('idx_tasting_brew_id', table_name='tasting')
    op.drop_table('tasting')
    op.drop_index('idx_brew_user_id', table_name='brew')
    op.drop_index('idx_brew_method_id', table_name='brew')
    op.drop_index('idx_brew_brewed_at', table_name='brew')
    op.drop_index('idx_brew_bean_id', table_name='brew')
    op.drop_table('brew')
    op.drop_index('idx_bean_user_id', table_name='bean')
    op.drop_index('idx_bean_roaster', table_name='bean')
    op.drop_table('bean')
    op.drop_table('user')
    op.drop_table('equipment')
    op.drop_table('brew_method')
    # ### end Alembic commands ###
