"""add brew.user_id author

Revision ID: 3773876ecced
Revises: 8da2ccfdf21e
Create Date: 2026-07-11 12:54:22.524040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3773876ecced'
down_revision: Union[str, Sequence[str], None] = '8da2ccfdf21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brew', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index('idx_brew_user_id', 'brew', ['user_id'], unique=False)
    op.create_foreign_key(None, 'brew', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brew', type_='foreignkey')
    op.drop_index('idx_brew_user_id', table_name='brew')
    op.drop_column('brew', 'user_id')
    # ### end Alembic commands ###
