/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppRoastersRouteImport } from './routes/_app/roasters'
import { Route as AppEquipmentRouteImport } from './routes/_app/equipment'
import { Route as AppBrewMethodsRouteImport } from './routes/_app/brew-methods'
import { Route as AppBeansRouteImport } from './routes/_app/beans'
import { Route as AppBrewsIndexRouteImport } from './routes/_app/brews/index'
import { Route as AppBrewsBrewIdRouteImport } from './routes/_app/brews/$brewId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppRoastersRoute = AppRoastersRouteImport.update({
  id: '/roasters',
  path: '/roasters',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppBrewMethodsRoute = AppBrewMethodsRouteImport.update({
  id: '/brew-methods',
  path: '/brew-methods',
  getParentRoute: () => AppRoute,
} as any)
const AppBeansRoute = AppBeansRouteImport.update({
  id: '/beans',
  path: '/beans',
  getParentRoute: () => AppRoute,
} as any)
const AppBrewsIndexRoute = AppBrewsIndexRouteImport.update({
  id: '/brews/',
  path: '/brews/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrewsBrewIdRoute = AppBrewsBrewIdRouteImport.update({
  id: '/brews/$brewId',
  path: '/brews/$brewId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/signup': typeof SignupRoute
  '/beans': typeof AppBeansRoute
  '/brew-methods': typeof AppBrewMethodsRoute
  '/equipment': typeof AppEquipmentRoute
  '/roasters': typeof AppRoastersRoute
  '/users': typeof AppUsersRoute
  '/brews/$brewId': typeof AppBrewsBrewIdRoute
  '/brews/': typeof AppBrewsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/signup': typeof SignupRoute
  '/beans': typeof AppBeansRoute
  '/brew-methods': typeof AppBrewMethodsRoute
  '/equipment': typeof AppEquipmentRoute
  '/roasters': typeof AppRoastersRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/brews/$brewId': typeof AppBrewsBrewIdRoute
  '/brews': typeof AppBrewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/beans': typeof AppBeansRoute
  '/_app/brew-methods': typeof AppBrewMethodsRoute
  '/_app/equipment': typeof AppEquipmentRoute
  '/_app/roasters': typeof AppRoastersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/brews/$brewId': typeof AppBrewsBrewIdRoute
  '/_app/brews/': typeof AppBrewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/signup'
    | '/beans'
    | '/brew-methods'
    | '/equipment'
    | '/roasters'
    | '/users'
    | '/brews/$brewId'
    | '/brews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/signup'
    | '/beans'
    | '/brew-methods'
    | '/equipment'
    | '/roasters'
    | '/users'
    | '/'
    | '/brews/$brewId'
    | '/brews'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/recover-password'
    | '/signup'
    | '/_app/beans'
    | '/_app/brew-methods'
    | '/_app/equipment'
    | '/_app/roasters'
    | '/_app/users'
    | '/_app/'
    | '/_app/brews/$brewId'
    | '/_app/brews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roasters': {
      id: '/_app/roasters'
      path: '/roasters'
      fullPath: '/roasters'
      preLoaderRoute: typeof AppRoastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brew-methods': {
      id: '/_app/brew-methods'
      path: '/brew-methods'
      fullPath: '/brew-methods'
      preLoaderRoute: typeof AppBrewMethodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beans': {
      id: '/_app/beans'
      path: '/beans'
      fullPath: '/beans'
      preLoaderRoute: typeof AppBeansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brews/': {
      id: '/_app/brews/'
      path: '/brews'
      fullPath: '/brews/'
      preLoaderRoute: typeof AppBrewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brews/$brewId': {
      id: '/_app/brews/$brewId'
      path: '/brews/$brewId'
      fullPath: '/brews/$brewId'
      preLoaderRoute: typeof AppBrewsBrewIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBeansRoute: typeof AppBeansRoute
  AppBrewMethodsRoute: typeof AppBrewMethodsRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppRoastersRoute: typeof AppRoastersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrewsBrewIdRoute: typeof AppBrewsBrewIdRoute
  AppBrewsIndexRoute: typeof AppBrewsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeansRoute: AppBeansRoute,
  AppBrewMethodsRoute: AppBrewMethodsRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppRoastersRoute: AppRoastersRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrewsBrewIdRoute: AppBrewsBrewIdRoute,
  AppBrewsIndexRoute: AppBrewsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
