/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppEquipmentRouteImport } from './routes/_app/equipment'
import { Route as AppBrewMethodsRouteImport } from './routes/_app/brew-methods'
import { Route as AppRoastersIndexRouteImport } from './routes/_app/roasters/index'
import { Route as AppBrewsIndexRouteImport } from './routes/_app/brews/index'
import { Route as AppBeansIndexRouteImport } from './routes/_app/beans/index'
import { Route as AppRoastersRoasterIdRouteImport } from './routes/_app/roasters/$roasterId'
import { Route as AppBrewsBrewIdRouteImport } from './routes/_app/brews/$brewId'
import { Route as AppBeansBeanIdRouteImport } from './routes/_app/beans/$beanId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppBrewMethodsRoute = AppBrewMethodsRouteImport.update({
  id: '/brew-methods',
  path: '/brew-methods',
  getParentRoute: () => AppRoute,
} as any)
const AppRoastersIndexRoute = AppRoastersIndexRouteImport.update({
  id: '/roasters/',
  path: '/roasters/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrewsIndexRoute = AppBrewsIndexRouteImport.update({
  id: '/brews/',
  path: '/brews/',
  getParentRoute: () => AppRoute,
} as any)
const AppBeansIndexRoute = AppBeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoastersRoasterIdRoute = AppRoastersRoasterIdRouteImport.update({
  id: '/roasters/$roasterId',
  path: '/roasters/$roasterId',
  getParentRoute: () => AppRoute,
} as any)
const AppBrewsBrewIdRoute = AppBrewsBrewIdRouteImport.update({
  id: '/brews/$brewId',
  path: '/brews/$brewId',
  getParentRoute: () => AppRoute,
} as any)
const AppBeansBeanIdRoute = AppBeansBeanIdRouteImport.update({
  id: '/beans/$beanId',
  path: '/beans/$beanId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/brew-methods': typeof AppBrewMethodsRoute
  '/equipment': typeof AppEquipmentRoute
  '/users': typeof AppUsersRoute
  '/beans/$beanId': typeof AppBeansBeanIdRoute
  '/brews/$brewId': typeof AppBrewsBrewIdRoute
  '/roasters/$roasterId': typeof AppRoastersRoasterIdRoute
  '/beans/': typeof AppBeansIndexRoute
  '/brews/': typeof AppBrewsIndexRoute
  '/roasters/': typeof AppRoastersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/brew-methods': typeof AppBrewMethodsRoute
  '/equipment': typeof AppEquipmentRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/beans/$beanId': typeof AppBeansBeanIdRoute
  '/brews/$brewId': typeof AppBrewsBrewIdRoute
  '/roasters/$roasterId': typeof AppRoastersRoasterIdRoute
  '/beans': typeof AppBeansIndexRoute
  '/brews': typeof AppBrewsIndexRoute
  '/roasters': typeof AppRoastersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/brew-methods': typeof AppBrewMethodsRoute
  '/_app/equipment': typeof AppEquipmentRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/beans/$beanId': typeof AppBeansBeanIdRoute
  '/_app/brews/$brewId': typeof AppBrewsBrewIdRoute
  '/_app/roasters/$roasterId': typeof AppRoastersRoasterIdRoute
  '/_app/beans/': typeof AppBeansIndexRoute
  '/_app/brews/': typeof AppBrewsIndexRoute
  '/_app/roasters/': typeof AppRoastersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/brew-methods'
    | '/equipment'
    | '/users'
    | '/beans/$beanId'
    | '/brews/$brewId'
    | '/roasters/$roasterId'
    | '/beans/'
    | '/brews/'
    | '/roasters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/brew-methods'
    | '/equipment'
    | '/users'
    | '/'
    | '/beans/$beanId'
    | '/brews/$brewId'
    | '/roasters/$roasterId'
    | '/beans'
    | '/brews'
    | '/roasters'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_app/brew-methods'
    | '/_app/equipment'
    | '/_app/users'
    | '/_app/'
    | '/_app/beans/$beanId'
    | '/_app/brews/$brewId'
    | '/_app/roasters/$roasterId'
    | '/_app/beans/'
    | '/_app/brews/'
    | '/_app/roasters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brew-methods': {
      id: '/_app/brew-methods'
      path: '/brew-methods'
      fullPath: '/brew-methods'
      preLoaderRoute: typeof AppBrewMethodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roasters/': {
      id: '/_app/roasters/'
      path: '/roasters'
      fullPath: '/roasters/'
      preLoaderRoute: typeof AppRoastersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brews/': {
      id: '/_app/brews/'
      path: '/brews'
      fullPath: '/brews/'
      preLoaderRoute: typeof AppBrewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beans/': {
      id: '/_app/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof AppBeansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roasters/$roasterId': {
      id: '/_app/roasters/$roasterId'
      path: '/roasters/$roasterId'
      fullPath: '/roasters/$roasterId'
      preLoaderRoute: typeof AppRoastersRoasterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brews/$brewId': {
      id: '/_app/brews/$brewId'
      path: '/brews/$brewId'
      fullPath: '/brews/$brewId'
      preLoaderRoute: typeof AppBrewsBrewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beans/$beanId': {
      id: '/_app/beans/$beanId'
      path: '/beans/$beanId'
      fullPath: '/beans/$beanId'
      preLoaderRoute: typeof AppBeansBeanIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrewMethodsRoute: typeof AppBrewMethodsRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBeansBeanIdRoute: typeof AppBeansBeanIdRoute
  AppBrewsBrewIdRoute: typeof AppBrewsBrewIdRoute
  AppRoastersRoasterIdRoute: typeof AppRoastersRoasterIdRoute
  AppBeansIndexRoute: typeof AppBeansIndexRoute
  AppBrewsIndexRoute: typeof AppBrewsIndexRoute
  AppRoastersIndexRoute: typeof AppRoastersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrewMethodsRoute: AppBrewMethodsRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppBeansBeanIdRoute: AppBeansBeanIdRoute,
  AppBrewsBrewIdRoute: AppBrewsBrewIdRoute,
  AppRoastersRoasterIdRoute: AppRoastersRoasterIdRoute,
  AppBeansIndexRoute: AppBeansIndexRoute,
  AppBrewsIndexRoute: AppBrewsIndexRoute,
  AppRoastersIndexRoute: AppRoastersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
